export const theme = {
  colors: {
    primary: '#1A3673',
    primaryLight: '#2A4E9E',
    primaryDark: '#0E214D',
    primaryMuted: '#EBF2FF',
    accent: '#00A86B',
    accentLight: '#E6F9F1',
    secondary: '#82F3B2',
    gold: '#D97706',
    goldLight: '#FEF3C7',
    crimson: '#E11D48',
    crimsonLight: '#FFE4E6',
    purple: '#7C3AED',
    purpleLight: '#F3E8FF',
    background: '#F8FAFC',
    surface: '#FFFFFF',
    surfaceSubtle: '#F1F5F9',
    card: '#FFFFFF',
    border: '#E2E8F0',
    borderLight: '#F1F5F9',
    textPrimary: '#0F172A',
    textSecondary: '#64748B',
    textMuted: '#94A3B8',
    white: '#FFFFFF',
    black: '#000000',
    overlay: 'rgba(15, 23, 42, 0.6)',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
    xxxl: 32,
  },
  borderRadius: {
    sm: 6,
    md: 10,
    lg: 14,
    xl: 20,
    full: 9999,
  },
  typography: {
    fontFamily: {
      regular: 'System',
      medium: 'System',
      bold: 'System',
    },
    sizes: {
      xs: 11,
      sm: 13,
      md: 15,
      lg: 17,
      xl: 20,
      xxl: 24,
      title: 28,
    },
  },
  touchTarget: {
    minHeight: 48,
    minWidth: 48,
  },
  shadows: {
    sm: {
      shadowColor: '#0F172A',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    md: {
      shadowColor: '#0F172A',
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.08,
      shadowRadius: 6,
      elevation: 3,
    },
    lg: {
      shadowColor: '#0F172A',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.12,
      shadowRadius: 12,
      elevation: 6,
    },
  },
};

export type AppTheme = typeof theme;
