export const theme = {
  colors: {
    primary: '#1A3673',
    primaryLight: '#2A4E9E',
    primaryDark: '#0E214D',
    primaryMuted: '#EBF2FF',
    accent: '#00A86B',
    accentLight: '#E6F9F1',
    secondary: '#82F3B2',
    gold: '#D97706',
    goldLight: '#FEF3C7',
    crimson: '#E11D48',
    crimsonLight: '#FFE4E6',
    purple: '#7C3AED',
    purpleLight: '#F3E8FF',
    background: '#F8FAFC',
    surface: '#FFFFFF',
    surfaceSubtle: '#F1F5F9',
    card: '#FFFFFF',
    border: '#E2E8F0',
    borderLight: '#F1F5F9',
    textPrimary: '#0F172A',
    textSecondary: '#64748B',
    textMuted: '#94A3B8',
    white: '#FFFFFF',
    black: '#000000',
    overlay: 'rgba(15, 23, 42, 0.6)',
    divider: '#EDF1F7',
    ring: 'rgba(26, 54, 115, 0.10)',
    tintWash: 'rgba(26, 54, 115, 0.04)',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
    xxxl: 32,
  },
  borderRadius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 22,
    xxl: 28,
    full: 9999,
  },
  typography: {
    fontFamily: {
      regular: 'System',
      medium: 'System',
      bold: 'System',
    },
    sizes: {
      xs: 11,
      sm: 13,
      md: 15,
      lg: 17,
      xl: 20,
      xxl: 24,
      title: 28,
      display: 34,
    },
    weights: {
      medium: '500',
      semibold: '600',
      bold: '700',
      heavy: '800',
      black: '900',
    } as const,
    letterSpacing: {
      tight: -0.3,
      normal: 0,
      wide: 0.5,
      wider: 1,
    },
  },
  touchTarget: {
    minHeight: 48,
    minWidth: 48,
  },
  // Shadows are tinted with the brand navy rather than black, which reads softer on the light background.
  shadows: {
    xs: {
      shadowColor: '#1A3673',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 3,
      elevation: 1,
    },
    sm: {
      shadowColor: '#1A3673',
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.07,
      shadowRadius: 8,
      elevation: 2,
    },
    md: {
      shadowColor: '#1A3673',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.1,
      shadowRadius: 16,
      elevation: 5,
    },
    lg: {
      shadowColor: '#1A3673',
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.14,
      shadowRadius: 28,
      elevation: 10,
    },
  },
};

export type AppTheme = typeof theme;
